development:
  :access_key_id: 'AKIAJCFW4YGYRHMW655A'
  :secret_access_key: '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'
  :s3_bucket_name: 'soginationaltest'
  :s3_host_name: 'https://soginationaltest.s3-ap-southeast-1.amazonaws.com'
  :s3_region: 'ap-southeast-1'
  :rds_server_name: 'test'
  :rds_region: 'ap-southeast-1'

test:
  :access_key_id: ''
  :secret_access_key: ''
  :s3_bucket_name: '''your_my_aws_s3_bucket_name'''
  :s3_host_name: '''http://my_aws.s3-ap-southeast-1.amazonaws.com'''
  :s3_region: '''ap-southeast-1'''
  :rds_server_name: '''your_rds_server_name'''
  :rds_region: '''ap-southeast-1'''

production:
  :access_key_id: 'AKIAJCFW4YGYRHMW655A'
  :secret_access_key: 'u55uvgkeWL2UB6gHLur9aMZK5COeGsEfMOhrPvQi'
  :s3_bucket_name: 'soginationaltest'
  :s3_host_name: 'https://soginationaltest.s3-ap-southeast-1.amazonaws.com'
  :s3_region: 'ap-southeast-1'
  :rds_server_name: 'test'
  :rds_region: 'ap-southeast-1'